package com.java.coreTemplate.model.dto;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;
import java.util.Optional;

@Entity
@Table(name = "validator.py")
@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class Validatorpy {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "name", nullable = false, length = 100)
    private String name;

    @Column(name = "is_active")
    private boolean isActive;

    @Column(name = "is_verified")
    private boolean isVerified;

    @Column(name = "email", unique = true, length = 255)
    private String email;

    @Column(name = "created_at", updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at")
    private Instant updatedAt;

    @Column(name = "score", precision = 5, scale = 2)
    private Double score;

    @Version
    private Long version;

    // Boolean getters with 'is' prefix are automatically generated by Lombok
    // Example: isActive(), isVerified()

    @PrePersist
    protected void onCreate() {
        this.createdAt = Instant.now();
        this.updatedAt = Instant.now();
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = Instant.now();
    }

    // Optional getter example for nullable field
    public Optional<Double> getScore() {
        return Optional.ofNullable(score);
    }
}